### PR TITLE
Update .Net to 6

### LINKED ISSUE #10: Update to .Net Core / .Net
As there are no GitHub Actions for .Net Framework, for #9 to be completed, the .Net version must first be upgraded

### PR DESCRIPTION
**Pull request by mdawsonuk**
Fixes #10

### CODE REVIEW

**Comment by stuajnht** [comment]
Hi @mdawsonuk, a couple of things:

1. Could you change the PR to merge into the `develop` branch instead of `master` please?
2. I've pushed a release of Version 0.3 this evening, so you may want to update / rebase this PR with the updated files
3. In #10 you've mentioned we'll be going .net Framework 4.0 -> .net 6.0 -> .net 8.0 (in the future) -- does this PR title need to be amended as it mentions .net 7.0?
4. Unless I'm missing something, so far you've renamed the `Tests` directories? I'm assuming more migration "stuff" is to come?

**Comment by mdawsonuk** [comment]
> Hi @mdawsonuk, a couple of things:
> 
> 1. Could you change the PR to merge into the `develop` branch instead of `master` please?
> 2. I've pushed a release of Version 0.3 this evening, so you may want to update / rebase this PR with the updated files
> 3. In [Update to .Net Core / .Net #10](https://github.com/CSSS-Games/CSSS/issues/10) you've mentioned we'll be going .net Framework 4.0 -> .net 6.0 -> .net 8.0 (in the future) -- does this PR title need to be amended as it mentions .net 7.0?
> 4. Unless I'm missing something, so far you've renamed the `Tests` directories? I'm assuming more migration "stuff" is to come?

1. Done
2. Done
3. Done - initally I wasn't sure which version of .Net to upgrade to, but .Net 6.0 makes more sense given it is LTS
4. Yes, more stuff will come over the next few days - I'm just opening it as a draft PR so you have visibility over the current work 👍🏻

**Comment by mdawsonuk** [comment]
Looks like we'll need to migrate away from the Windows Form NotifyIcon and find something that works as well but is also cross-platform, as you can't include System.Windows.Forms on non-Windows specific projects

**Comment by stuajnht** [comment]
Thanks @mdawsonuk! Appreciate your help getting this project running on a newer version of .net, and for the new workflow CI/CD actions.

**Pull request merged**
